version: '3'
networks:
    ml-simian-network:
        driver: bridge
services:
    mysql_service:
        build:
            dockerfile: ./docker_images/mysql.dockerfile
            context: .
        image: mysql_image
        container_name: mysql_service
        ports:
            - "3306:3306"
        networks:
            - ml-simian-network
    analysis_service:
        build:
            dockerfile: ./docker_images/analysis_server.dockerfile
            context: .
        image: analysis_service_image
        container_name: analysis_service
        command: bash -c "java -jar target/ml-simian-analysis-1.0.jar db migrate config.yml && java -jar target/ml-simian-analysis-1.0.jar server config.yml"
        ports:
            - "8080:8080"
            - "8081:8081"
        networks:
            - ml-simian-network
        depends_on:
            - mysql_service
    stats_service:
        build:
            dockerfile: ./docker_images/stats_server.dockerfile
            context: .
        image: stats_service_image
        container_name: stats_service
        command: java -jar target/ml-simian-stats-1.0.jar server config.yml
        ports:
            - "8090:8090"
            - "8091:8091"
        networks:
            - ml-simian-network
        depends_on:
            - mysql_service
            - analysis_service